// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIjUNtWSqYIazISOXc4y4gD-yVWDeB4L8',
    appId: '1:459128624272:web:aaddd248ceea102f69b415',
    messagingSenderId: '459128624272',
    projectId: 'pastaboardproject',
    authDomain: 'pastaboardproject.firebaseapp.com',
    databaseURL: 'https://pastaboardproject-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pastaboardproject.appspot.com',
    measurementId: 'G-6H0F0RRJTC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN6wz-8I6IXTQHUlzmFVYQnqIe49be71Y',
    appId: '1:459128624272:android:0209c6eb80487be269b415',
    messagingSenderId: '459128624272',
    projectId: 'pastaboardproject',
    databaseURL: 'https://pastaboardproject-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pastaboardproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd81HvfUzYky8oe1Cwp6ivip_vz0pNVuo',
    appId: '1:459128624272:ios:d1631415a0aedfc669b415',
    messagingSenderId: '459128624272',
    projectId: 'pastaboardproject',
    databaseURL: 'https://pastaboardproject-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pastaboardproject.appspot.com',
    iosBundleId: 'com.example.pastaBoard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBd81HvfUzYky8oe1Cwp6ivip_vz0pNVuo',
    appId: '1:459128624272:ios:546bf9f1805bb38c69b415',
    messagingSenderId: '459128624272',
    projectId: 'pastaboardproject',
    databaseURL: 'https://pastaboardproject-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pastaboardproject.appspot.com',
    iosBundleId: 'com.example.pastaBoard.RunnerTests',
  );
}
